FROM alpine-base

ARG PG_VERSION
ENV PG_MAJOR=${PG_VERSION}
ENV PATH=/usr/lib/postgresql/${PG_MAJOR}/bin:$PATH 

RUN apk add postgresql${PG_MAJOR} --repository=http://dl-cdn.alpinelinux.org/alpine/v3.20/community